clc;
clear;
close all;
[filename, pathname, filterindex]=uigetfile('*.*', 'Pick an Imange file');
filename=strcat(pathname,filename);
a=imread(filename);
imshow(a);
b=rgb2gray(a);
figure;
imshow(b);
%figure;
%imhist(b);
impixelinfo;
c=imbinarize(b,20/255);
figure;
imshow(c);
%d=imfill(c,'holes');
%figure;
%imshow(d);
%e=bwareaopen(c,1000);
%figure;
%imshow(e);
preprocessedImage=uint8(double(a).*repmat(c,[1 1 3]));
figure;
imshow(preprocessedImage);
preprocessedImage=imadjust(preprocessedImage,[0.4 0.7],[])+50;
figure;
imshow(preprocessedImage);
uo=rgb2gray(preprocessedImage);
figure;
imshow(uo);
mo=medfilt2(uo,[5 5]);
figure;
imshow(mo);
po=mo>250;
figure;
imshow(po);
[r, c, m]=size(po);
x1=r/3;
y1=c/3;
row=[x1+100 x1+250 x1+250 x1+100];
col=[y1 y1 y1+130 y1+130];
BW=roipoly(po,row,col);
figure;
imshow(BW);
k=po.*double(BW);
figure;
imshow(k);
M=bwareaopen(k,4);
[ya, number]=bwlabel(M);
if(number>=1) 
    disp('Tumor is Detected');
else
    disp('No Tumor is Detected');
end